# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    milestone: 23

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "development"
    ignore:
      - dependency-name: "oliverklee/oelib"
      - dependency-name: "phpunit/phpunit"
        versions: [ ">= 9.0.0" ]
      - dependency-name: "psr/log"
      - dependency-name: "symfony/console"
      - dependency-name: "symfony/translation"
      - dependency-name: "symfony/yaml"
      - dependency-name: "typo3/testing-framework"
        versions: [ ">= 8.0.0" ]
      - dependency-name: "typo3/coding-standards"
        versions: [ ">= 0.7.0" ]
    versioning-strategy: "increase"
    milestone: 23
