<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-09-07 15:32

$extensionPath = t3lib_extMgm::extPath('onetimeaccount');
return array(
	'tx_onetimeaccount_configcheck' => $extensionPath . 'class.tx_onetimeaccount_configcheck.php',
	'tx_onetimeaccount_eid' => $extensionPath . 'class.tx_onetimeaccount_eid.php',
	'tx_onetimeaccount_tests_fixtures_fakepi1' => $extensionPath . 'Tests/Fixtures/FakePi1.php',
	'tx_onetimeaccount_pi1' => $extensionPath . 'pi1/class.tx_onetimeaccount_pi1.php',
	'tx_onetimeaccount_pi1_wizicon' => $extensionPath . 'pi1/class.tx_onetimeaccount_pi1_wizicon.php',
);
?>